version: '2'
services:
  morgue:
    build:
      context: ./
      dockerfile: Dockerfile-morgue
    links:
      - morguedb
    environment:
      MORGUE_ENVIRONMENT: docker
      MORGUE_DB_HOST: morguedb
      MORGUE_DB_NAME: morgue
      MORGUE_DB_USER: morgue
      MORGUE_DB_PASS: password
    ports:
      - 80:80
  morguedb:
    image: mysql:5
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_ONETIME_PASSWORD: 'yes'
      MYSQL_DATABASE: morgue
      MYSQL_USER: morgue
      MYSQL_PASSWORD: password
